version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cranios_db
      POSTGRES_USER: cranios_user
      POSTGRES_PASSWORD: cranios_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cranios-net

  redis:
    image: redis:7
    networks:
      - cranios-net

  n8n:
    image: n8nio/n8n
    ports:
      - "5680:5678"  # 🔄 Porta externa ajustada
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=cranios_db
      - DB_POSTGRESDB_USER=cranios_user
      - DB_POSTGRESDB_PASSWORD=cranios_pass
      - QUEUE_MODE=redis
      - QUEUE_REDIS_HOST=redis
      - WEBHOOK_URL=http://localhost:5679/
      - WEBHOOK_TUNNEL_URL=http://localhost:5679/
    depends_on:
      - postgres
      - redis
    networks:
      - cranios-net

  cranios-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "./start.sh"]
    depends_on:
      - postgres
      - redis
    networks:
      - cranios-net
    volumes:
      - .:/app  # ✅ Garante que os arquivos sejam visíveis
    environment:
      - PYTHONUNBUFFERED=1

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "celery_app", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - cranios-app
    networks:
      - cranios-net
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

networks:
  cranios-net:

volumes:
  postgres_data:
