version: '3.8'

# Removida a definição de rede customizada 'cranios-network'
# O Docker Compose criará uma rede padrão onde todos os serviços se verão.

volumes:
  postgres_data:
  redis_data:
  n8n_data:
  evolution_data:
  evolution_store:
  

services:
  # 1. Aplicação Principal (Backend)
  cranios-app:
    build: .
    container_name: cranios-main
    command: sh -c "cd /app && ./start.sh"
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    # Removida a rede customizada. Usará a rede padrão do Docker Compose.
    # Adicionada a label para o Traefik apontar para a porta correta.
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.cranios-app.loadbalancer.server.port=5678"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      # A URL da Evolution API agora aponta para localhost na porta exposta.
      - EVOLUTION_API_URL=http://localhost:8090
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - ARCEE_API_KEY=${ARCEE_API_KEY}
      - GOOGLE_DRIVE_CREDENTIALS=${GOOGLE_DRIVE_CREDENTIALS}
      - AUTENTIQUE_API_KEY=${AUTENTIQUE_API_KEY}
    volumes:
      - ./app:/app
      - ./logs:/app/logs

  # 2. N8N - Automação de Workflows
  n8n:
    image: n8nio/n8n:latest
    container_name: cranios-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    depends_on:
      - postgres
    # Removida a rede customizada. Usará a rede padrão do Docker Compose.
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      # A URL do webhook agora aponta para localhost na porta exposta.
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - DB_TYPE=postgresdb
      # O host do banco de dados agora aponta para o nome do serviço.
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_files:/files

  # 3. Evolution API - WhatsApp
  evolution-api:
    image: atendai/evolution-api:latest
    container_name: cranios-evolution
    restart: unless-stopped
    ports:
      - "8090:8080"
    depends_on:
      - postgres
      - redis
    # Removida a rede customizada. Usará a rede padrão do Docker Compose.
    environment:
      # A URL do servidor agora aponta para localhost na porta exposta.
      - SERVER_URL=http://localhost:8090
      - CORS_ORIGIN=*
      - CORS_METHODS=GET,POST,PUT,DELETE
      - CORS_CREDENTIALS=true
      - LOG_LEVEL=ERROR
      - DATABASE_ENABLED=true
      # A URL do banco de dados agora aponta para o nome do serviço.
      - DATABASE_CONNECTION_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/evolution
      - REDIS_ENABLED=true
      # A URL do Redis agora aponta para o nome do serviço.
      - REDIS_URI=redis://redis:6379
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
      # A URL do webhook global agora aponta para localhost na porta exposta do N8N.
      - WEBHOOK_GLOBAL_URL=http://localhost:5678/webhook/whatsapp
      - WEBHOOK_GLOBAL_ENABLED=true
    volumes:
      - evolution_data:/evolution/instances
      - evolution_store:/evolution/store

  # 4. Banco de Dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: cranios-postgres
    restart: unless-stopped
    # Removida a rede customizada. Usará a rede padrão do Docker Compose.
    environment:
      - POSTGRES_DB=cranios
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=n8n,evolution
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh

  # 5. Cache Redis
  redis:
    image: redis:7-alpine
    container_name: cranios-redis
    restart: unless-stopped
    # Removida a rede customizada. Usará a rede padrão do Docker Compose.
    volumes:
      - redis_data:/data

  # 6. Celery Worker
  celery-worker:
    build: .
    container_name: cranios-celery
    command: sh -c "cd /app && celery -A celery_app worker --loglevel=info"
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    # Removida a rede customizada. Usará a rede padrão do Docker Compose.
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      # A URL da Evolution API agora aponta para localhost na porta exposta.
      - EVOLUTION_API_URL=http://localhost:8090
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - ARCEE_API_KEY=${ARCEE_API_KEY}
      # A URL do Redis agora aponta para localhost na porta exposta.
      - REDIS_URL=redis://localhost:6379/0
    volumes:
      - ./app:/app
      - ./logs:/app/logs

  # 7. Celery Beat
  celery-beat:
    build: .
    container_name: cranios-beat
    command: sh -c "cd /app && celery -A celery_app beat --loglevel=info"
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    # Removida a rede customizada. Usará a rede padrão do Docker Compose.
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      # A URL do Redis agora aponta para localhost na porta exposta.
      - REDIS_URL=redis://localhost:6379/0
    volumes:
      - ./app:/app
      - ./logs:/app/logs

 
